pipelines:
  default:
    - step:
        name: Build JavaScript
        image: node:latest
        caches: 
          - node
        script:
          - cd src/main/javascript
          - npm test --watchAll=false
          - npm run build
        artifacts:
          - src/main/javascript/build/**
    - step:
        name: Build Java and package all files
        image: maven:latest
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn -B package # -B batch mode makes Maven less verbose
        artifacts:
          - target/*.jar